#!/bin/bash
echo "Content-Type: text/plain"
echo ""
echo "CGI Test Results:"
echo "=================="
echo "REQUEST_METHOD: $REQUEST_METHOD"
echo "SCRIPT_NAME: $SCRIPT_NAME"
echo "PATH_INFO: [$PATH_INFO]"
echo "QUERY_STRING: $QUERY_STRING"
echo "SERVER_NAME: $SERVER_NAME"
echo "SERVER_PORT: $SERVER_PORT"
echo "Date: $(date)"
echo "CGI working correctly!"